### ISSUE TITLE
text_writer.py only functions is list of strings passed

### ISSUE THREAD

**Issue by daniel-partington** [daniel-partington/HydroModelBuilder#13]
@ConnectedSystems , in [text_writer.py](https://github.com/daniel-partington/HydroModelBuilder/blob/dev-working/HydroModelBuilder/Utilities/text_writer.py) I think we need to convert any list objects to __str__ in the "join" calls. In PESTInterface, the file writing was done using objects of type __float__, __int__ as well as __str__.

**Comment by ConnectedSystems** [comment]
@daniel-partington can this issue be closed?

**Comment by daniel-partington** [comment]
Yes
